### ISSUE TITLE
The method 'nextDouble' was called on null.

### ISSUE THREAD

**Issue by xingqiyi** [HarrisonQi/flame-tutorial-langaw#1]
出现异常。
NoSuchMethodError (NoSuchMethodError: The method 'nextDouble' was called on null.
Receiver: null
Tried calling: nextDouble())

void initialize() async {
//下面这2句是不是  应该有先后顺序
    rnd = Random();
    spawner = FlySpawner(this);

**Comment by HarrisonQi** [comment]
这两句:
```dart
rnd = Random();
spawner = FlySpawner(this);
```
的先后顺序不会产生报错.

检查下调用`rnd.nextDouble()`前, 是否已经初始化了`rnd`.

如果找不到问题所在, 可直接复制仓库源码, 和自己的代码进行比较.

**Comment by HarrisonQi** [comment]
看来问题解决了, 我将关闭这个issue😃
